### PR TITLE
Remove tests as they are not self-contained or deterministic

### LINKED ISSUE #7: Tests never really quit
As a developer, when I run `make test`, I expect the tests process to stop when all the tests are OK.
However, the tracker tests never quit. I have to manually (ctrl + c) stop them.

This is due to the timer.

Two solution : 
- Add a method to quit the timer (proposed by @sandcha)
```
we can add this code and call stop_test(tracker):

    def stop_test(tracker):
        def stop_timer(tracker):
            return
        tracker.stop_timer = types.MethodType(stop_timer, PiwikTracker)
```

- Only start the timer when at least 1 request is waiting to be sent.

### PR DESCRIPTION
**Pull request by Morendil**
Fixes #7 

Rationale: the current tests rely on interaction with an external online resource, plus manual inspection of run results, and so do not qualify as truly "automated" checks. In addition they require manual intervention to exit, which make them unsuitable for CI purposes. We are no worse off removing them altogether.

I'm not even sure we should be implementing our own async task queue based on Python's threading primitives, they are notoriously hard to get right and to debug. On the other hand, recent task queue packages like Dramatiq tend to require Redis and that's arguably overkill.

### CODE REVIEW

**Comment by sandcha** [comment]
@Morendil What about moving this content to a new file in a `/scripts` directory instead of deleting it?

**Comment by Morendil** [comment]
@sandcha If you consider that a fix for #7. In any case, feel free to do what you think best :)

**Comment by sandcha** [comment]
I would rather clean the tests than delete what was started. 
Here is an alternative to this PR: #10

**Review by sandcha — CHANGES_REQUESTED** [review]
I would rather clean the tests than delete what was started.
Here is an alternative to this PR: #10

**Comment by Morendil** [comment]
Closing in favor of #10

**Pull request closed without merging**
