### PR TITLE
Make style checks stricter and clearer

### PR DESCRIPTION
**Pull request by bonjourmauko**
* Technical improvement.
* Impacted areas: `**/*`
* Details:
  - Make style checks stricter and clearer to help developers contribute

### CODE REVIEW

**Comment by Br3nda** [comment]
There's no circle-ci running on this PR

**Review by Br3nda — CHANGES_REQUESTED** [review]
Can the lint be checked by CI please.

**Comment by Br3nda** [comment]
Hi - if we move these checks to github workflows, we'll get comments inline on the pull request.

**Review by Br3nda — APPROVED** [review]
LGTM

**Comment by bonjourmauko** [comment]
I haven't yet checked Github workflows 😄

**Pull request merged**
